[theme]
base = "light"
primaryColor = "#087f79"
backgroundColor = "#f3f6f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#172c40"
font = "sans-serif"

[client]
disableDataExport = true
toolbarMode = "minimal"
showErrorDetails = "none"
